### ISSUE TITLE
Ship goes too fast crosswind

### ISSUE THREAD

**Issue by dcoollx** [cbcerquiaga/BootyHunter#60]
When crossing the world bounds, the player ship gains a large boost of speed and exceeds the maximum speed until direction is changed

**Comment by cbcerquiaga** [comment]
Does it matter what direction the wind is coming from?

**Comment by cbcerquiaga** [comment]
I've played around with it I think it's something else. If the player just goes in one direction and hits the max speed, there is not issue with going over the max speed. The problem is when the ship is going downwind, builds up speed, and then turns. Instead of slowing down to 300 like it should, the ship maintains its current speed.

**Comment by cbcerquiaga** [comment]
Turns out we were checking to see if the player's x and y velocities were greater than MAX_SPEED. If the ship is going up or left, those values are negative, so we should have been checking against the absolute value and "increasing" the velocity if it's below 0.
